services:
  core:
    image: satantime/puppeteer-node:24.14.0
    platform: linux/amd64
    working_dir: /app
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - .:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --omit=optional

volumes:
  cache:
  npm:
  gyp:
