services:
  core:
    image: satantime/puppeteer-node:26.7.0
    platform: linux/amd64
    working_dir: /app
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - PUPPETEER_SKIP_CHROME_DOWNLOAD=true
    volumes:
      - .:/app
      - cache:/root/.cache
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - ci
      - --no-audit
      - --omit=optional

volumes:
  cache:
  npm:
  gyp:
