services:
  core:
    image: satantime/puppeteer-node:22.8.0
    working_dir: /app
    volumes:
      - .:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --omit=optional

volumes:
  npm:
  gyp:
