import './test.spec.ts';

import './examples/MockBuilder/test.deep.spec.ts';
import './examples/MockBuilder/test.ng-mocks.spec.ts';
import './examples/MockBuilder/test.promise.spec.ts';
import './examples/MockBuilder/test.simple.spec.ts';
import './examples/MockComponent/test.spec.ts';
import './examples/MockDirective-Attribute/test.spec.ts';
import './examples/MockDirective-Structural/test.spec.ts';
import './examples/MockForms/test.spec.ts';
import './examples/MockInstance/test.spec.ts';
import './examples/MockModule/test.spec.ts';
import './examples/MockObservable/test.spec.ts';
import './examples/MockPipe/test.spec.ts';
import './examples/MockProvider/test.spec.ts';
import './examples/MockReactiveForms/test.spec.ts';
import './examples/MockRender/test.spec.ts';
import './examples/MockSanitizer/test.spec.ts';
import './examples/MockViewChild/test.spec.ts';
import './examples/TestAttributeDirective/test.spec.ts';
import './examples/TestHttpInterceptor/test.spec.ts';
import './examples/TestHttpRequest/test.spec.ts';
import './examples/TestLazyModule/test.spec.ts';
import './examples/TestLifecycleHooks/test.spec.ts';
import './examples/TestLifecycleHooks/test.string.spec.ts';
import './examples/TestLifecycleHooks/test.type-without-params.spec.ts';
import './examples/TestMultiToken/test.spec.ts';
import './examples/TestPipe/test.spec.ts';
import './examples/TestProvider/test.spec.ts';
import './examples/TestProviderInComponent/test.spec.ts';
import './examples/TestProviderInDirective/test.spec.ts';
import './examples/TestProviderWithDependencies/test.spec.ts';
import './examples/TestProviderWithUseClass/test.spec.ts';
import './examples/TestProviderWithUseExisting/test.spec.ts';
import './examples/TestProviderWithUseFactory/test.spec.ts';
import './examples/TestProviderWithUseValue/test.spec.ts';
import './examples/TestRoute/test.spec.ts';
import './examples/TestRoutingGuard/test.spec.ts';
import './examples/TestRoutingResolver/test.spec.ts';
import './examples/TestStructuralDirective/test.spec.ts';
import './examples/TestStructuralDirectiveWithContext/test.spec.ts';
import './examples/TestTemplateRefByDirective/test.spec.ts';
import './examples/TestTemplateRefById/test.spec.ts';
import './examples/TestTemplateRefByRender/test.spec.ts';
import './examples/TestToken/test.spec.ts';
import './examples/TestViewChild/test.spec.ts';
import './examples/main/test.spec.ts';
import './examples/ngMocksFaster/test.spec.ts';
import './examples/ngMocksGuts/test.spec.ts';
import './examples/readme/test.spec.ts';

// // uncomment stuff below to run our e2e tests
// import './tests/NG_MOCKS_ROOT_PROVIDERS/test.spec.ts';
// import './tests/abstract-methods-provider/test.spec.ts';
// import './tests/auto-spy/test.spec.ts';
// import './tests/context-with-directives/test.spec.ts';
// import './tests/control-value-accessor-form-control/test.spec.ts';
// import './tests/control-value-accessor-ng-model/test.spec.ts';
// import './tests/correct-module-exports-11/test.spec.ts';
// import './tests/double-decorator/example-1.spec.ts';
// import './tests/double-decorator/example-2.spec.ts';
// import './tests/double-decorator/example-3.spec.ts';
// import './tests/double-decorator/with-selector.spec.ts';
// import './tests/double-decorator/without-selector-ivy.spec.ts';
// import './tests/double-decorator/without-selector.spec.ts';
// import './tests/export-all/test.spec.ts';
// import './tests/exports-only/test.spec.ts';
// import './tests/fake-async/test.spec.ts';
// import './tests/flex-exact-mocks/test.spec.ts';
// import './tests/get-inputs-and-outputs/test.spec.ts';
// import './tests/get-mocked-ng-def-of/test.spec.ts';
// import './tests/injected-ng-templates/test.spec.ts';
// import './tests/interceptor-kept-mocked/test.spec.ts';
// import './tests/internal-only-nested/test.spec.ts';
// import './tests/internal-only/test.spec.ts';
// import './tests/internal-vs-external/test.spec.ts';
// import './tests/is-mock-of/test.spec.ts';
// import './tests/is-mocked-ng-def-of/test.spec.ts';
// import './tests/issue-142/test.spec.ts';
// import './tests/issue-145/components.spec.ts';
// import './tests/issue-145/directives.spec.ts';
// import './tests/issue-151/test.spec.ts';
// import './tests/issue-157/test.spec.ts';
// import './tests/issue-162/test.spec.ts';
// import './tests/issue-166/test.spec.ts';
// import './tests/issue-167/component.spec.ts';
// import './tests/issue-167/directive.spec.ts';
// import './tests/issue-167/ng-validators.spec.ts';
// import './tests/issue-170/test.spec.ts';
// import './tests/issue-172/test.spec.ts';
// import './tests/issue-173/test.spec.ts';
// import './tests/issue-175/test.spec.ts';
// import './tests/issue-177/test.spec.ts';
// import './tests/issue-178/test.spec.ts';
// import './tests/issue-181/test.spec.ts';
// import './tests/issue-186/test.spec.ts';
// import './tests/issue-197/abstract.spec.ts';
// import './tests/issue-197/with-providers.spec.ts';
// import './tests/issue-218/test.spec.ts';
// import './tests/issue-222/app-initializer.spec.ts';
// import './tests/issue-222/application-module.spec.ts';
// import './tests/issue-222/common-module.spec.ts';
// import './tests/issue-222/dom-shared-styles-host.spec.ts';
// import './tests/issue-222/injector-scope.spec.ts';
// import './tests/issue-222/injector.spec.ts';
// import './tests/issue-222/kept-root-injection.spec.ts';
// import './tests/issue-222/mock-keep-priorities.spec.ts';
// import './tests/issue-240/test.builder.spec.ts';
// import './tests/issue-240/test.classic.spec.ts';
// import './tests/issue-240/test.guts.spec.ts';
// import './tests/issue-240/test.nodes.spec.ts';
// import './tests/issue-240/test.real.spec.ts';
// import './tests/issue-241/test.builder.spec.ts';
// import './tests/issue-241/test.classic.spec.ts';
// import './tests/issue-241/test.guts.spec.ts';
// import './tests/issue-241/test.real.spec.ts';
// import './tests/issue-246/test.spec.ts';
// import './tests/issue-248/test.spec.ts';
// import './tests/issue-266/test.spec.ts';
// import './tests/issue-270/test.spec.ts';
// import './tests/issue-271/test.spec.ts';
// import './tests/issue-288/ng-model.spec.ts';
// import './tests/issue-288/test.spec.ts';
// import './tests/issue-289/test.spec.ts';
// import './tests/issue-296/test.spec.ts';
// import './tests/issue-298/case.spec.ts';
// import './tests/issue-298/pipes.spec.ts';
// import './tests/issue-298/stack-blitz.spec.ts';
// import './tests/issue-298/test.spec.ts';
// import './tests/issue-302/test.spec.ts';
// import './tests/issue-305/forms.spec.ts';
// import './tests/issue-305/overrides.spec.ts';
// import './tests/issue-305/reactive-forms.spec.ts';
// import './tests/issue-312/test.spec.ts';
// import './tests/issue-333/test.spec.ts';
// import './tests/issue-354/test.spec.ts';
// import './tests/issue-377/e2e.spec.ts';
// import './tests/issue-377/test.spec.ts';
// import './tests/issue-434/test.spec.ts';
// import './tests/issue-435/test.spec.ts';
// import './tests/issue-445/test.spec.ts';
// import './tests/issue-455/abstract.spec.ts';
// import './tests/issue-455/token.spec.ts';
// import './tests/issue-488/faster.spec.ts';
// import './tests/issue-488/test.spec.ts';
// import './tests/issue-522/test.spec.ts';
// import './tests/issue-537/test.spec.ts';
// import './tests/issue-538/test.spec.ts';
// import './tests/issue-567/test.spec.ts';
// import './tests/issue-568/test.spec.ts';
// import './tests/issue-572/test.spec.ts';
// import './tests/issue-576/test.spec.ts';
// import './tests/issue-589/test.spec.ts';
// import './tests/issue-621/test.spec.ts';
// import './tests/issue-625/test.spec.ts';
// import './tests/issue-641/test.spec.ts';
// import './tests/mock-builder-by-directive/test.spec.ts';
// import './tests/mock-builder-keeps-application-module/test.spec.ts';
// import './tests/mock-component-render/content-child.spec.ts';
// import './tests/mock-component-render/content-children-groups.spec.ts';
// import './tests/mock-component-render/content-children.spec.ts';
// import './tests/mock-component-render/hide.spec.ts';
// import './tests/mock-component-render/reduced.spec.ts';
// import './tests/mock-directive-with-multi-token/test.spec.ts';
// import './tests/mock-instance-in-it/test.spec.ts';
// import './tests/mock-instance-member/reset.spec.ts';
// import './tests/mock-instance-member/test.spec.ts';
// import './tests/mock-instance-token/test.spec.ts';
// import './tests/mock-render-all-properties/test.spec.ts';
// import './tests/mock-render-factory/docs.spec.ts';
// import './tests/mock-render-factory/install.spec.ts';
// import './tests/mock-render-factory/test.spec.ts';
// import './tests/mock-render-factory/tpl.spec.ts';
// import './tests/mock-render-mirrors-component/test.spec.ts';
// import './tests/mock-render-param-ref/test.spec.ts';
// import './tests/mock-render-tokens/test.spec.ts';
// import './tests/mock-service-override/test.spec.ts';
// import './tests/module-with-factory-tokens/test.spec.ts';
// import './tests/module-with-tokens/test.spec.ts';
// import './tests/multi-tokens/test.spec.ts';
// import './tests/nested-before-each/test.spec.ts';
// import './tests/ng-mocks-change/317.spec.ts';
// import './tests/ng-mocks-change/cdr-change.spec.ts';
// import './tests/ng-mocks-change/cdr-input.spec.ts';
// import './tests/ng-mocks-change/forms.spec.ts';
// import './tests/ng-mocks-change/reactive-forms.spec.ts';
// import './tests/ng-mocks-click/317.spec.ts';
// import './tests/ng-mocks-crawl/317.spec.ts';
// import './tests/ng-mocks-crawl/test.spec.ts';
// import './tests/ng-mocks-default-mock/test.builder.spec.ts';
// import './tests/ng-mocks-default-mock/test.guts.spec.ts';
// import './tests/ng-mocks-default-mock/test.precise.spec.ts';
// import './tests/ng-mocks-default-mock/test.real.spec.ts';
// import './tests/ng-mocks-default-mock/test.unset.spec.ts';
// import './tests/ng-mocks-find-all/test.spec.ts';
// import './tests/ng-mocks-find-instance-token/test.spec.ts';
// import './tests/ng-mocks-find-instance/317.spec.ts';
// import './tests/ng-mocks-find-instance/abstract.spec.ts';
// import './tests/ng-mocks-find-instance/test.spec.ts';
// import './tests/ng-mocks-find-instances/317.spec.ts';
// import './tests/ng-mocks-find-instances/test.spec.ts';
// import './tests/ng-mocks-find-template-ref/317.spec.ts';
// import './tests/ng-mocks-find-template-ref/test.spec.ts';
// import './tests/ng-mocks-find-template-refs/317.spec.ts';
// import './tests/ng-mocks-find-template-refs/test.spec.ts';
// import './tests/ng-mocks-find/test.spec.ts';
// import './tests/ng-mocks-format-html/test.spec.ts';
// import './tests/ng-mocks-format-text/test.spec.ts';
// import './tests/ng-mocks-get/317.spec.ts';
// import './tests/ng-mocks-global-exclude-modules/test.spec.ts';
// import './tests/ng-mocks-global-exclude/test.override.spec.ts';
// import './tests/ng-mocks-global-exclude/test.spec.ts';
// import './tests/ng-mocks-global-keep-modules/test.spec.ts';
// import './tests/ng-mocks-global-keep/test.override.spec.ts';
// import './tests/ng-mocks-global-keep/test.spec.ts';
// import './tests/ng-mocks-global-mock/test.spec.ts';
// import './tests/ng-mocks-global-replace-modules/test.spec.ts';
// import './tests/ng-mocks-global-replace/test.component.spec.ts';
// import './tests/ng-mocks-global-replace/test.directive.spec.ts';
// import './tests/ng-mocks-global-replace/test.failures.spec.ts';
// import './tests/ng-mocks-global-replace/test.override.spec.ts';
// import './tests/ng-mocks-global-replace/test.pipe.spec.ts';
// import './tests/ng-mocks-global-wipe/test.spec.ts';
// import './tests/ng-mocks-input/317.spec.ts';
// import './tests/ng-mocks-output/317.spec.ts';
// import './tests/ng-mocks-render/cdr.spec.ts';
// import './tests/ng-mocks-render/component.spec.ts';
// import './tests/ng-mocks-render/debug-node.spec.ts';
// import './tests/ng-mocks-render/directive.spec.ts';
// import './tests/ng-mocks-render/idea.spec.ts';
// import './tests/ng-mocks-render/params.spec.ts';
// import './tests/ng-mocks-render/use-existing.spec.ts';
// import './tests/ng-mocks-reveal-all/317.spec.ts';
// import './tests/ng-mocks-reveal/317.spec.ts';
// import './tests/ng-mocks-reveal/test.spec.ts';
// import './tests/ng-mocks-search-with-no-fixture/test.fixture.spec.ts';
// import './tests/ng-mocks-search-with-no-fixture/test.no-fixture.spec.ts';
// import './tests/ng-mocks-stub-member/test.spec.ts';
// import './tests/ng-mocks-stub/test.spec.ts';
// import './tests/ng-mocks-throw-on-console/test.spec.ts';
// import './tests/ng-mocks-touch/317.spec.ts';
// import './tests/ng-mocks-touch/cdr-blur.spec.ts';
// import './tests/ng-mocks-touch/cdr-touch.spec.ts';
// import './tests/ng-mocks-touch/test.spec.ts';
// import './tests/ng-mocks-trigger/317.spec.ts';
// import './tests/ng-mocks-trigger/blur.spec.ts';
// import './tests/ng-mocks-trigger/click.spec.ts';
// import './tests/ng-mocks-trigger/focus.spec.ts';
// import './tests/ng-mocks-trigger/keyup.spec.ts';
// import './tests/ng-mocks-trigger/test.spec.ts';
// import './tests/ng-zone/test.spec.ts';
// import './tests/normal-usage-after-mock-builder/test.spec.ts';
// import './tests/on-push/on-push.spec.ts';
// import './tests/performance/test.spec.ts';
// import './tests/pipe-as-service/test.spec.ts';
// import './tests/pipe-auto-spy/test.spec.ts';
// import './tests/provider-with-custom-dependencies/test.spec.ts';
// import './tests/provider-with-dependency/test.spec.ts';
// import './tests/replace-service-wherever/test.spec.ts';
// import './tests/rerender-rendered-content-child/test.spec.ts';
// import './tests/root-provider-in-depths/test.spec.ts';
// import './tests/root-provider-with-root-dep/test.spec.ts';
// import './tests/root-provider-with-string-dep/test.spec.ts';
// import './tests/root-providers/test.spec.ts';
// import './tests/shared-mocked-module/test.spec.ts';
// import './tests/spies/test.spec.ts';
// import './tests/structural-directives/test.spec.ts';
// import './tests/tokens-class/test.spec.ts';
// import './tests/tokens-existing/test.spec.ts';
// import './tests/tokens-factory/test.spec.ts';
// import './tests/tokens-value/test.spec.ts';
