import "./test.spec.ts";

import "./examples/MAIN/test.spec.ts";
import "./examples/MockBuilder/test.spec.ts";
import "./examples/MockComponent/test.spec.ts";
import "./examples/MockDirective-Attribute/test.spec.ts";
import "./examples/MockDirective-Structural/test.spec.ts";
import "./examples/MockForms/test.spec.ts";
import "./examples/MockInstance/test.spec.ts";
import "./examples/MockModule/test.spec.ts";
import "./examples/MockObservable/test.spec.ts";
import "./examples/MockPipe/test.spec.ts";
import "./examples/MockProvider/test.spec.ts";
import "./examples/MockReactiveForms/test.spec.ts";
import "./examples/MockRender/test.spec.ts";
import "./examples/NG_MOCKS/NG_MOCKS.spec.ts";
import "./examples/TestAttributeDirective/test.spec.ts";
import "./examples/TestHttpInterceptor/test.spec.ts";
import "./examples/TestHttpRequest/test.spec.ts";
import "./examples/TestLifecycleHooks/test.spec.ts";
import "./examples/TestMultiToken/test.spec.ts";
import "./examples/TestPipe/test.spec.ts";
import "./examples/TestProvider/test.spec.ts";
import "./examples/TestProviderInComponent/test.spec.ts";
import "./examples/TestProviderInDirective/test.spec.ts";
import "./examples/TestProviderWithDependencies/test.spec.ts";
import "./examples/TestProviderWithUseClass/test.spec.ts";
import "./examples/TestProviderWithUseExisting/test.spec.ts";
import "./examples/TestProviderWithUseFactory/test.spec.ts";
import "./examples/TestProviderWithUseValue/test.spec.ts";
import "./examples/TestRoute/test.spec.ts";
import "./examples/TestRoutingGuard/test.spec.ts";
import "./examples/TestRoutingResolver/test.spec.ts";
import "./examples/TestStructuralDirective/test.spec.ts";
import "./examples/TestStructuralDirectiveWithContext/test.spec.ts";
import "./examples/TestToken/test.spec.ts";
import "./examples/ngMocksFaster/test.spec.ts";
import "./examples/ngMocksGuts/test.spec.ts";

// // uncomment stuff below to run our e2e tests
// import "./tests/NG_MOCKS_ROOT_PROVIDERS/test.spec.ts";
// import "./tests/abstract-methods-provider/test.spec.ts";
// import "./tests/context-with-directives/context-with-directives.spec.ts";
// import "./tests/control-value-accessor-form-control/test.spec.ts";
// import "./tests/control-value-accessor-ng-model/test.spec.ts";
// import "./tests/correct-module-exports-11/test.spec.ts";
// import "./tests/double-decorator/example-1.spec.ts";
// import "./tests/double-decorator/example-2.spec.ts";
// import "./tests/double-decorator/example-3.spec.ts";
// import "./tests/double-decorator/with-selector.spec.ts";
// import "./tests/double-decorator/without-selector-ivy.spec.ts";
// import "./tests/double-decorator/without-selector.spec.ts";
// import "./tests/export-all/test.spec.ts";
// import "./tests/exports-only/test.spec.ts";
// import "./tests/get-inputs-and-outputs/test.spec.ts";
// import "./tests/get-mocked-ng-def-of/test.spec.ts";
// import "./tests/injected-ng-templates/injected-ng-templates.spec.ts";
// import "./tests/interceptor-kept-mocked/test.spec.ts";
// import "./tests/internal-only-nested/test.spec.ts";
// import "./tests/internal-only/test.spec.ts";
// import "./tests/internal-vs-external/test.spec.ts";
// import "./tests/is-mock-of/test.spec.ts";
// import "./tests/is-mocked-ng-def-of/test.spec.ts";
// import "./tests/issue-142/test.spec.ts";
// import "./tests/issue-145/components.spec.ts";
// import "./tests/issue-145/directives.spec.ts";
// import "./tests/issue-151/test.spec.ts";
// import "./tests/issue-157/test.spec.ts";
// import "./tests/issue-162/test.spec.ts";
// import "./tests/issue-166/test.spec.ts";
// import "./tests/issue-167/NG_VALIDATORS.spec.ts";
// import "./tests/issue-167/component.spec.ts";
// import "./tests/issue-167/directive.spec.ts";
// import "./tests/issue-170/test.spec.ts";
// import "./tests/issue-172/test.spec.ts";
// import "./tests/issue-173/test.spec.ts";
// import "./tests/issue-175/test.spec.ts";
// import "./tests/issue-177/test.spec.ts";
// import "./tests/issue-178/test.spec.ts";
// import "./tests/issue-181/test.spec.ts";
// import "./tests/issue-186/test.spec.ts";
// import "./tests/issue-197/abstract.spec.ts";
// import "./tests/issue-197/with-providers.spec.ts";
// import "./tests/issue-218/test.spec.ts";
// import "./tests/issue-222/app-initializer.spec.ts";
// import "./tests/issue-222/application-module.spec.ts";
// import "./tests/issue-222/common-module.spec.ts";
// import "./tests/issue-222/dom-shared-styles-host.spec.ts";
// import "./tests/issue-222/injector-scope.spec.ts";
// import "./tests/issue-222/injector.spec.ts";
// import "./tests/issue-222/kept-root-injection.spec.ts";
// import "./tests/issue-222/mock-keep-priorities.spec.ts";
// import "./tests/mock-builder-by-directive/test.spec.ts";
// import "./tests/mock-builder-keeps-application-module/test.spec.ts";
// import "./tests/mock-render-all-properties/test.spec.ts";
// import "./tests/mock-render-mirrors-component/test.spec.ts";
// import "./tests/mock-service-override/test.spec.ts";
// import "./tests/module-with-factory-tokens/test.spec.ts";
// import "./tests/module-with-tokens/test.spec.ts";
// import "./tests/multi-tokens/test.spec.ts";
// import "./tests/nested-before-each/test.spec.ts";
// import "./tests/ng-mocks-search-with-no-fixture/test.spec.ts";
// import "./tests/normal-usage-after-mock-builder/test.spec.ts";
// import "./tests/on-push/on-push.spec.ts";
// import "./tests/performance/test.spec.ts";
// import "./tests/pipe-as-service/test.spec.ts";
// import "./tests/provider-with-custom-dependencies/test.spec.ts";
// import "./tests/provider-with-dependency/test.spec.ts";
// import "./tests/replace-service-wherever/test.spec.ts";
// import "./tests/rerender-rendered-content-child/test.spec.ts";
// import "./tests/root-provider-in-depths/test.spec.ts";
// import "./tests/root-provider-with-root-dep/test.spec.ts";
// import "./tests/root-provider-with-string-dep/test.spec.ts";
// import "./tests/root-providers/test.spec.ts";
// import "./tests/shared-mocked-module/test.spec.ts";
// import "./tests/spies/test.spec.ts";
// import "./tests/structural-directives/structural-directives.spec.ts";
// import "./tests/tokens-class/test.spec.ts";
// import "./tests/tokens-existing/test.spec.ts";
// import "./tests/tokens-factory/test.spec.ts";
// import "./tests/tokens-value/test.spec.ts";
